books_list = [
    {'first_name': 'Дуглас', 'last_name': 'Адамс', 'avatar': None, 'genres': ['Научная фантастика', 'Фэнтези'], 'title': 'Путеводитель для путешествующих автостопом по галактике', 'price': 707, 'pages': 215},
    {'first_name': 'Джордж', 'last_name': 'Мартин', 'avatar': None, 'genres': ['Научная фантастика'], 'title': 'Игра престолов', 'price': 450, 'pages': 700},
    {'first_name': 'Джордж', 'last_name': 'Оруэлл', 'avatar': None, 'genres': ['Антиутопия', 'Политическая фантастика'], 'title': '1984', 'price': 250, 'pages': 328},
    {'first_name': 'Рэй', 'last_name': 'Брэдбери', 'avatar': None, 'genres': ['Научная фантастика', 'Фэнтези'], 'title': '451 градус по Фаренгейту', 'price': 200, 'pages': 174},
    {'first_name': 'Харпер', 'last_name': 'Ли', 'avatar': None, 'genres': ['Романы', 'Историческая литература'], 'title': 'Убить пересмешника', 'price': 300, 'pages': 324},
    {'first_name': 'Маргарет', 'last_name': 'Митчелл', 'avatar': None, 'genres': ['Романы', 'Историческая литература'], 'title': 'Унесенные ветром', 'price': 400, 'pages': 1037},
    {'first_name': 'Джейн', 'last_name': 'Остин', 'avatar': None, 'genres': ['Романы', 'Романтика'], 'title': 'Гордость и предубеждение', 'price': 270, 'pages': 279},
    {'first_name': 'Лев', 'last_name': 'Толстой', 'avatar': None, 'genres': ['Эпопея', 'Историческая литература'], 'title': 'Война и мир', 'price': 500, 'pages': 1392},
    {'first_name': 'Федор', 'last_name': 'Достоевский', 'avatar': None, 'genres': ['Психологическая проза', 'Философская проза'], 'title': 'Преступление и наказание', 'price': 350, 'pages': 672},
    {'first_name': 'Антон', 'last_name': 'Чехов', 'avatar': None, 'genres': ['Драма', 'Пьесы'], 'title': 'Чайка', 'price': 150, 'pages': 96},
    {'first_name': 'Александр', 'last_name': 'Пушкин', 'avatar': None, 'genres': ['Поэзия', 'Драма'], 'title': 'Евгений Онегин', 'price': 180, 'pages': 224},
    {'first_name': 'Михаил', 'last_name': 'Лермонтов', 'avatar': None, 'genres': ['Поэзия', 'Романтизм'], 'title': 'Герой нашего времени', 'price': 200, 'pages': 160},
    {'first_name': 'Иван', 'last_name': 'Тургенев', 'avatar': None, 'genres': ['Романы', 'Реализм'], 'title': 'Отцы и дети', 'price': 250, 'pages': 240},
    {'first_name': 'Николай', 'last_name': 'Гоголь', 'avatar': None, 'genres': ['Повести', 'Реализм'], 'title': 'Мертвые души', 'price': 300, 'pages': 424},
]
